### ISSUE TITLE
Goals list page

### ISSUE THREAD

**Issue by Nikola-xiii** [Nikola-xiii/goals-manager#3]
Elements in a list item: 
- Objectives
- Key
- Results

### TODO

- [x] Create list item component
- [x] Create list view container
- [x] Create goal list route 
- [x] Connect container to Store
