### ISSUE TITLE
Goal single page

### ISSUE THREAD

**Issue by Nikola-xiii** [Nikola-xiii/goals-manager#4]
### Elements on the page
- Objective
- Key
- Results
- Button "Add task"

### TODO
- [x] Add id field for Goal type
- [x] Create single goal container
- [x] Create goal/id route
- [x] Add action for get single goal
