### ISSUE TITLE
Task list on Goal Page

### ISSUE THREAD

**Issue by Nikola-xiii** [Nikola-xiii/goals-manager#6]
- [x] Add task model and expand goal type with task field
- [x] Create TaskList component
- [x] Add Task list component to Single goal component
- [x] Style done task
